In [1]:
import pandas as pd

In [4]:
data=pd.read_csv("/Users/karishmadev/Downloads/sales_data_1.csv")
data

,Date,Firm bought from,Buying price,Customer,Selling price,Quantity sold
0,21/08/23,Vendor6,72.11,Customer7,91.58,44
1,21/08/23,Vendor4,75.08,Customer7,83.71,17
2,21/08/23,Vendor7,83.93,Customer2,103.76,15
3,21/08/23,Vendor7,52.01,Customer3,64.53,7
4,21/08/23,Vendor2,98.91,Customer5,140.92,1
...,...,...,...,...,...,...
65,27/08/23,Vendor4,64.82,Customer6,87.45,18
66,27/08/23,Vendor8,88.79,Customer3,105.59,5
67,27/08/23,Vendor5,63.30,Customer5,92.92,32
68,27/08/23,Vendor5,94.06,Customer5,125.67,4
69,27/08/23,Vendor5,56.28,Customer6,82.16,1

In [15]:
# 1. GROSS MARGIN FOR THEIR BUSINESS

data['Gross_Margin'] = data['Buying price'] - data['Selling price']
overall_gross_margin =data['Gross_Margin'].sum()
print("Overall Gross Margin for the business: ", overall_gross_margin)

Overall Gross Margin for the business:  -1207.1999999999998

In [16]:
# 2. MOST PROFTIABLE VENDOR:

vendor_profit = data.groupby('Firm bought from')['Gross_Margin'].sum().idxmax()
print("Most profitable vendor: ", vendor_profit)

Most profitable vendor:  Vendor6

In [17]:
# 3. LEAST PROFTIABLE VENDOR:

customer_profit = data.groupby('Customer')['Gross_Margin'].sum().idxmin()
print("Least profitable customer: ", customer_profit)

Least profitable customer:  Customer8

In [18]:
# 4. MOST PROFTIABLE DAY OF THE WEEK:

data['Date'] = pd.to_datetime(data['Date'])
data['Day_of_Week'] = data['Date'].dt.day_name()
most_profitable_day = data.groupby('Day_of_Week')['Gross_Margin'].sum().idxmax()
print("Most profitable day of the week: ", most_profitable_day)

Most profitable day of the week:  Thursday

In [19]:
# 5. LEAST PROFTIABLE DAY OF THE WEEK:

least_profitable_day = data.groupby('Day_of_Week')['Gross_Margin'].sum().idxmin()
print("Least profitable day of the week: ", least_profitable_day)

Least profitable day of the week:  Monday

In [21]:

data_2=pd.read_csv("/Users/karishmadev/Downloads/sales_data_2.csv")
data_2

,Date,Firm bought from,Buying price,Quantity bought,Customer,Selling price,Quantity sold
0,2023-08-21,Vendor6,72.11,60,Customer7,91.58,44
1,2023-08-21,Vendor4,75.08,92,Customer7,83.71,17
2,2023-08-21,Vendor7,83.93,16,Customer2,103.76,15
3,2023-08-21,Vendor7,52.01,62,Customer3,64.53,7
4,2023-08-21,Vendor2,98.91,1,Customer5,140.92,1
...,...,...,...,...,...,...,...
65,2023-08-27,Vendor4,64.82,28,Customer6,87.45,18
66,2023-08-27,Vendor8,88.79,14,Customer3,105.59,5
67,2023-08-27,Vendor5,63.30,81,Customer5,92.92,32
68,2023-08-27,Vendor5,94.06,18,Customer5,125.67,4
69,2023-08-27,Vendor5,56.28,25,Customer6,82.16,1

In [38]:
data_2['Gross_Profit'] = data_2['Selling price'] - data_2['Buying price']
print(data_2)

          Date Firm bought from  Buying price  Quantity bought   Customer  \
0   2023-08-21          Vendor6         72.11               60  Customer7
1   2023-08-21          Vendor4         75.08               92  Customer7
2   2023-08-21          Vendor7         83.93               16  Customer2
3   2023-08-21          Vendor7         52.01               62  Customer3
4   2023-08-21          Vendor2         98.91                1  Customer5
..         ...              ...           ...              ...        ...
65  2023-08-27          Vendor4         64.82               28  Customer6
66  2023-08-27          Vendor8         88.79               14  Customer3
67  2023-08-27          Vendor5         63.30               81  Customer5
68  2023-08-27          Vendor5         94.06               18  Customer5
69  2023-08-27          Vendor5         56.28               25  Customer6

    Selling price  Quantity sold  Gross_Profit  3_day_avg_profit  \
0           91.58             44         19.47               NaN
1           83.71             17          8.63               NaN
2          103.76             15         19.83         15.976667
3           64.53              7         12.52         13.660000
4          140.92              1         42.01         24.786667
..            ...            ...           ...               ...
65          87.45             18         22.63         20.686667
66         105.59              5         16.80         22.173333
67          92.92             32         29.62         23.016667
68         125.67              4         31.61         26.010000
69          82.16              1         25.88         29.036667

    three_day_avg_profit
0                    NaN
1                    NaN
2              15.976667
3              13.660000
4              24.786667
..                   ...
65             20.686667
66             22.173333
67             23.016667
68             26.010000
69             29.036667

[70 rows x 10 columns]

In [39]:
data_2['3_day_avg_profit'] = data_2['Gross_Profit'].rolling(window=3).mean()
print(data_2)

          Date Firm bought from  Buying price  Quantity bought   Customer  \
0   2023-08-21          Vendor6         72.11               60  Customer7
1   2023-08-21          Vendor4         75.08               92  Customer7
2   2023-08-21          Vendor7         83.93               16  Customer2
3   2023-08-21          Vendor7         52.01               62  Customer3
4   2023-08-21          Vendor2         98.91                1  Customer5
..         ...              ...           ...              ...        ...
65  2023-08-27          Vendor4         64.82               28  Customer6
66  2023-08-27          Vendor8         88.79               14  Customer3
67  2023-08-27          Vendor5         63.30               81  Customer5
68  2023-08-27          Vendor5         94.06               18  Customer5
69  2023-08-27          Vendor5         56.28               25  Customer6

    Selling price  Quantity sold  Gross_Profit  3_day_avg_profit  \
0           91.58             44         19.47               NaN
1           83.71             17          8.63               NaN
2          103.76             15         19.83         15.976667
3           64.53              7         12.52         13.660000
4          140.92              1         42.01         24.786667
..            ...            ...           ...               ...
65          87.45             18         22.63         20.686667
66         105.59              5         16.80         22.173333
67          92.92             32         29.62         23.016667
68         125.67              4         31.61         26.010000
69          82.16              1         25.88         29.036667

    three_day_avg_profit
0                    NaN
1                    NaN
2              15.976667
3              13.660000
4              24.786667
..                   ...
65             20.686667
66             22.173333
67             23.016667
68             26.010000
69             29.036667

[70 rows x 10 columns]

In [29]:
# 4. PERCENTILES FOR BUYING PRICE:

buying_price_percentiles = data_2['Buying price'].quantile([0.25, 0.5, 0.75])
print("buying_price_percentiles:", buying_price_percentiles)

buying_price_percentiles: 0.25    29.90
0.50    60.76
0.75    78.32
Name: Buying price, dtype: float64

In [32]:
# 4. PERCENTILES FOR SELLING PRICE:

selling_price_percentiles = data_2['Selling price'].quantile([0.25, 0.5, 0.75])
print("selling_price_percentiles:", selling_price_percentiles)

selling_price_percentiles: 0.25     38.9750
0.50     78.9900
0.75    103.3975
Name: Selling price, dtype: float64

In [34]:
# 5. ANALYSING BUYIND=G AND SELLING PRICES AGANIST PERCENTILES:

below_25th_percentile = data_2[data_2['Buying price'] < buying_price_percentiles[0.25]]
print("below 25th percentile:", below_25th_percentile)

below 25th percentile:           Date Firm bought from  Buying price  Quantity bought    Customer  \
8   2023-08-21          Vendor1         20.95               95   Customer3
10  2023-08-22          Vendor5         27.71               33   Customer2
11  2023-08-22         Vendor10         10.48               80   Customer3
24  2023-08-23          Vendor7         27.75               22   Customer1
25  2023-08-23         Vendor10         10.19               42   Customer8
31  2023-08-24          Vendor6         14.76               19   Customer2
32  2023-08-24          Vendor7         26.29               55  Customer10
33  2023-08-24          Vendor5         18.66               68   Customer5
36  2023-08-24          Vendor7         24.75               20   Customer8
37  2023-08-24          Vendor2         17.24               52   Customer5
38  2023-08-24          Vendor2         14.30               85   Customer6
39  2023-08-24          Vendor7         15.42                9   Customer2
40  2023-08-25          Vendor2         17.82               60   Customer9
42  2023-08-25          Vendor1         17.62               81   Customer8
46  2023-08-25          Vendor2         11.13               22   Customer5
47  2023-08-25          Vendor8         10.31               70   Customer9
49  2023-08-25          Vendor4         17.85               80   Customer5
59  2023-08-26          Vendor4         28.90               88   Customer8

    Selling price  Quantity sold  Gross_Profit  3_day_avg_profit  \
8           24.48             22          3.53         28.256667
10          32.90             11          5.19          7.526667
11          14.31             40          3.83          7.626667
24          30.86              3          3.11         13.536667
25          11.65             25          1.46          5.883333
31          16.25              3          1.49         10.380000
32          38.53             55         12.24         11.293333
33          22.45             11          3.79          5.840000
36          31.49             19          6.74         21.663333
37          19.39             42          2.15         11.463333
38          18.81             57          4.51          4.466667
39          22.79              7          7.37          4.676667
40          22.13             58          4.31          5.396667
42          22.11             74          4.49         11.363333
46          14.78              4          3.65         20.400000
47          12.26              9          1.95         14.250000
49          20.47             20          2.62         13.780000
59          36.83             11          7.93         16.970000

    three_day_avg_profit
8              28.256667
10              7.526667
11              7.626667
24             13.536667
25              5.883333
31             10.380000
32             11.293333
33              5.840000
36             21.663333
37             11.463333
38              4.466667
39              4.676667
40              5.396667
42             11.363333
46             20.400000
47             14.250000
49             13.780000
59             16.970000

In [35]:
# ABOVE THE PERCENTILE RANGE:

above_75th_percentile = data_2[data_2['Selling price'] > selling_price_percentiles[0.75]]
print("above 75th percentile:", above_75th_percentile)

above 75th percentile:           Date Firm bought from  Buying price  Quantity bought    Customer  \
2   2023-08-21          Vendor7         83.93               16   Customer2
4   2023-08-21          Vendor2         98.91                1   Customer5
6   2023-08-21          Vendor2         74.34                7   Customer6
7   2023-08-21          Vendor3         98.11               62   Customer2
14  2023-08-22          Vendor9         80.15               34   Customer9
15  2023-08-22          Vendor9         92.70               23   Customer8
16  2023-08-22          Vendor7         89.79               61   Customer1
21  2023-08-23          Vendor3         71.96               70  Customer10
27  2023-08-23         Vendor10         93.29               68   Customer8
34  2023-08-24          Vendor4         99.23               95   Customer1
35  2023-08-24          Vendor7         93.63               94   Customer7
45  2023-08-25          Vendor3         92.54               28   Customer3
48  2023-08-25          Vendor7         87.36               68   Customer1
51  2023-08-26          Vendor7         94.29               34   Customer8
54  2023-08-26          Vendor4         82.77               66   Customer8
64  2023-08-27          Vendor9         77.18               59   Customer4
66  2023-08-27          Vendor8         88.79               14   Customer3
68  2023-08-27          Vendor5         94.06               18   Customer5

    Selling price  Quantity sold  Gross_Profit  3_day_avg_profit  \
2          103.76             15         19.83         15.976667
4          140.92              1         42.01         24.786667
6          106.93              6         32.59         32.130000
7          146.76             62         48.65         34.343333
14         109.71             20         29.56         19.526667
15         132.53              9         39.83         26.763333
16         111.92             25         22.13         30.506667
21         105.37             49         33.41         20.236667
27         135.33             41         42.04         15.986667
34         131.98             92         32.75         16.260000
35         119.13             23         25.50         20.680000
45         129.69             15         37.15         22.723333
48         124.13             34         36.77         14.123333
51         113.30             29         19.01         10.926667
54         124.13             65         41.36         25.790000
64         104.27             43         27.09         23.926667
66         105.59              5         16.80         22.173333
68         125.67              4         31.61         26.010000

    three_day_avg_profit
2              15.976667
4              24.786667
6              32.130000
7              34.343333
14             19.526667
15             26.763333
16             30.506667
21             20.236667
27             15.986667
34             16.260000
35             20.680000
45             22.723333
48             14.123333
51             10.926667
54             25.790000
64             23.926667
66             22.173333
68             26.010000